import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');
const CARD_WIDTH = (width - 48) / 2;
const colores = {
    fondo: "#F4F6FA",
    boton: "#0F2942",
    botonHover: "#253237",
    textoBoton: "#ffffff",
};

export const styles = StyleSheet.create({
inputContenedor: {
    flexDirection: 'row',          
    alignItems: 'center',         
    backgroundColor: '#CEDOCE',     
    borderWidth: 1,
    borderColor: '#5C6B73',       
    borderRadius: 18,             
    width: '90%',
    paddingHorizontal: 20,         
    paddingVertical: 4,            
    marginTop: 15,
    alignSelf: 'center',
  },
  inputIcono: {
    marginRight: 12,                
  },
  inputTexto: {
    flex: 1,                      
    paddingVertical: 12,           
    fontSize: 16,
    color: '#253237',             
  },
btnEntrar: {
    flexDirection: 'row',      
    alignItems: 'center',       
    justifyContent: 'center',    
    backgroundColor: '#0F2942',  
    borderRadius: 18,           
    paddingVertical: 15,         
    paddingHorizontal: 20,       
    marginVertical: 10,         
    width: '90%',             
    alignSelf: 'center',         
    elevation: 3,               
    shadowColor: '#F4F6FA',        
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
btnEntrarPressed: {
opacity: 0.8,
    transform: [{ scale: 0.98 }],
  },
btnIcono: {
    marginRight: 15,
    color: '#F4F6FA',            
  },

btnTexto: {
    color: '#F4F6FA',              
    fontSize: 18,               
    fontWeight: 'bold',         
  },
btnCambiarCuenta: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0F2942',  
    borderRadius: 18,           
    paddingVertical: 15,
    paddingHorizontal: 20,
    width: '90%',
    alignSelf: 'center',
    marginVertical: 10,
  },
btnCambiarCuentaPressed: {
    opacity: 0.85,
    transform: [{ scale: 0.98 }],
    },
pantallaprincipal: {
    flex: 1,
    backgroundColor: colores.fondo,
    alignItems: "center",
    justifyContent: "center",
},
btnCrearCuenta: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colores.boton,
    paddingVertical: 18,         
    paddingHorizontal: 24,               
    width: '90%',  
    borderRadius: 18,
    alignSelf: 'center',
    marginTop: 15,
},
btnCrearCuentaPressed: {
    backgroundColor: colores.botonHover, 
    transform: [{ scale: 0.98 }], 
},

btnCrearCuentaText: {
    fontSize: 18,
    fontWeight: "bold",
    color: '#F4F6FA',

    },
btndashboard: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colores.boton,
    paddingVertical: 18,         
    paddingHorizontal: 24,               
    width: '100%',  
    borderRadius: 18,
    alignSelf: 'center',
    marginTop: 15,
},
btndashboardPressed: {
    backgroundColor: colores.botonHover, 
    transform: [{ scale: 0.98 }], 
},
btndashboardText: {
    fontSize: 18,
    fontWeight: "bold",
    alignSelf: 'center',

    },
btnemergencia: {
    padding: 20, 
    borderRadius: 50,
    backgroundColor: "red",
    justifyContent: "center",
    alignItems: "center",
    elevation: 5,},

tarjetaRacha: {
   flexDirection: 'row',
    backgroundColor: '#253237', 
    width: '90%',
    padding: 20,
    borderRadius: 50, 
    alignItems: 'center',
    marginBottom: 25,
    borderWidth: 1,
    borderColor: '#334155', 
    elevation: 5, 
    shadowColor: '#000', 
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
  },
textoRachaValores: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 'bold',
  },
  textoRachaSubtitulo: {
    color: '#8A99A8',
    fontSize: 14,
  },
  tituloBienvenida: {
    color: '#FFFFFF',
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 20,
    alignSelf: 'flex-start', 
    marginLeft: '5%',
  },
  tarjetaContenedor: {
    backgroundColor: "E6E8E6",
    borderRadius: 20,
    padding: 15,
    width: "90%",
    alignSelf: "center",
    marginTop: 15,
    elevation: 2,
  },
  tarjetaTitulo: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#253237',
    marginBottom: 10,
  },
  lineaDivisoria: {
    height: 1,
    backgroundColor: '#CED0CE',
    marginBottom: 15,
    },
datoRenglon: {
    flexDirection: 'row',         
    alignItems: 'center',          
    paddingVertical: 8,           
  },
  datoIcono: {
    marginRight: 10,              
  },
  datoEtiqueta: {
    fontSize: 16,
    fontWeight: '600',
    color: '#5C6B73',              
    marginRight: 6,               
  },
  datoValor: {
    fontSize: 16,
    color: '#253237',              
    fontWeight: '400',
    flex: 1,                       
  },
  btnPresion: {
    width: "90%",
    backgroundColor: "#253237",
    padding: 15,
    borderRadius: 12,
    marginTop: 20,
    alignItems: "center"
  },
  btnPresion1: {
    width: "90%",
    backgroundColor: "#5C6B73",
    padding: 15,
    borderRadius: 12,
    marginTop: 20,
    alignItems: "center"
  },
  btnVolverPresion: {
    width: "90%",
    backgroundColor: "#9DB4C0",
    padding: 15,
    borderRadius: 12,
    marginTop: 20,
    alignItems: "center"
    },
    container: {
    flex: 1,
    backgroundColor: '#F4F6FA', 
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 50,
    paddingBottom: 30,
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  welcomeText: {
    fontSize: 26,
    fontWeight: '700',
    color: '#1E293B',
  },
  subtitleText: {
    fontSize: 14,
    color: '#64748B',
    marginTop: 2,
  },
  avatarCircle: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#E2E8F0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  streakBanner: {
    backgroundColor: '#0F2942', 
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
  },
  streakLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  fireCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  streakTextContainer: {
    justifyContent: 'center',
  },
  streakTitle: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 12,
    fontWeight: '600',
  },
  streakDays: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '800',
    marginVertical: 1,
  },
  streakDaysSub: {
    fontSize: 14,
    fontWeight: '400',
    color: 'rgba(255, 255, 255, 0.9)',
  },
  streakMotto: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  btnEmergencia: {
    backgroundColor: '#FF3B30', 
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
    shadowColor: '#FF3B30',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  btnEmergenciaPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.99 }],
  },
  sosLeftContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  bellCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  btnEmergenciaText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 16,
  },
  btnEmergenciaSub: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: 12,
    marginTop: 1,
  },
  gridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  card: {
    backgroundColor: '#FFFFFF',
    width: CARD_WIDTH,
    borderRadius: 16,
    padding: 14,
    marginBottom: 14,
    shadowColor: '#A0AEC0',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
  },
  cardPressed: {
    backgroundColor: '#F8FAFC',
    transform: [{ scale: 0.98 }],
  },
  iconCircle: {
    width: 44,
    height: 44,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1E293B',
    marginBottom: 4,
  },
  cardSub: {
    fontSize: 11,
    color: '#94A3B8',
    lineHeight: 14,
  },
  footerBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EFEFFF',
    borderRadius: 14,
    padding: 12,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  footerBannerTextContainer: {
    marginLeft: 10,
  },
  footerBannerTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#3F51B5',
  },
  footerBannerSub: {
    fontSize: 11,
    color: '#64748B',
    marginTop: 1,
  },
  btnVolver: {
    alignSelf: 'center',
    paddingVertical: 10,
    paddingHorizontal: 20,
  },
  btnVolverText: {
    color: '#94A3B8',
    fontWeight: '600',
    fontSize: 14,
  }
  });